### PR TITLE
Add Dockerfile for capstone project

### PR DESCRIPTION
**Pull request by olala7846**
I've created a docker file for the capstone project, hope this can save some time for other students.
to build the docker file
`docker build . -t capstone`
to run the docker file 
`docker run -p 127.0.0.1:4567:4567 -v $PWD:/capstone -v /tmp/log:/root/.ros/ --rm -it capstone`
cheers.

### CODE REVIEW

**Comment by olala7846** [comment]
Hi @ckirksey3, 
I don't know if I can make a PR to the Udacity repo like this, but please kindly take some time to look at this PR, thanks in advance 😄

**Comment by ckirksey3** [comment]
This is awesome! Thanks for the contribution. 

For posterity: I tested this out by building and running the container on OSX and then jumping inside, running catkin_make on the project, running roslaunch, and then verifying that topics were publishing correctly. 

I'll add you instructions to the readme in a separate PR.

**Comment by Mornor** [comment]
Just a (little) improvement, I would set up the working dir to `/capstone`: 
`docker run --rm -it -p 127.0.0.1:4567:4567 -v $PWD:/capstone -v /tmp/log:/root/.ros/ -w /capstone capstone`

Thanks a lot for this Dockerfile !

**Comment by Mornor** [comment]
I got the following error inside the container: 
```
root@16c1cb93df4e:/capstone/ros# catkin_make
Base path: /capstone/ros
Source space: /capstone/ros/src
Build space: /capstone/ros/build
Devel space: /capstone/ros/devel
Install space: /capstone/ros/install
####
#### Running command: "make cmake_check_build_system" in "/capstone/ros/build"
####
CMake Error: The source directory "/udacity/ros/src" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:1678: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
```
Did I forget something ?

Thanks a lot for the Dockerfile!

**Comment by olala7846** [comment]
@Mornor not sure why, mine catkin_make works fine, did you add any other module into the src folder
```
root@7687e082102c:/capstone/ros# catkin_make        
Base path: /capstone/ros  
Source space: /capstone/ros/src                     
Build space: /capstone/ros/build                    
Devel space: /capstone/ros/devel                    
Install space: /capstone/ros/install                
####                      
#### Running command: "make cmake_check_build_system" in "/capstone/ros/build"                           
####                      
####                      
#### Running command: "make -j2 -l2" in "/capstone/ros/build"                                            
####                      
[  0%] Built target std_msgs_generate_messages_lisp 
[  0%] Built target _styx_msgs_generate_messages_check_deps_Lane                                         
[  0%] Built target sensor_msgs_generate_messages_lisp                                                   
[  0%] Built target geometry_msgs_generate_messages_lisp                                                 
[  0%] Built target _styx_msgs_generate_messages_check_deps_TrafficLightArray                            
[  0%] Built target _styx_msgs_generate_messages_check_deps_TrafficLight                                 
[  0%] Built target std_msgs_generate_messages_eus  
[  0%] Built target _styx_msgs_generate_messages_check_deps_Waypoint                                     
[  0%] Built target sensor_msgs_generate_messages_eus                                                    
[  0%] Built target geometry_msgs_generate_messages_eus                                                  
[  0%] Built target std_msgs_generate_messages_nodejs                                                    
[  0%] Built target sensor_msgs_generate_messages_nodejs                                                 
[  0%] Built target geometry_msgs_generate_messages_nodejs                                               
[  0%] Built target std_msgs_generate_messages_cpp  
[  0%] Built target sensor_msgs_generate_messages_cpp                                                    
[  0%] Built target geometry_msgs_generate_messages_cpp                                                  
[  0%] Built target std_msgs_generate_messages_py   
[  0%] Built target sensor_msgs_generate_messages_py                                                     
[  0%] Built target geometry_msgs_generate_messages_py                                                   
[ 14%] Built target styx_msgs_generate_messages_lisp                                                     
[ 33%] Built target styx_msgs_generate_messages_eus 
[ 48%] Built target styx_msgs_generate_messages_nodejs                                                   
[ 62%] Built target styx_msgs_generate_messages_cpp 
[ 81%] Built target styx_msgs_generate_messages_py  
[ 81%] Built target styx_msgs_generate_messages     
[ 88%] Built target libwaypoint_follower            
[100%] Built target pure_pursuit                    
root@7687e082102c:/capstone/ros# 
```

**Comment by olala7846** [comment]
@Mornor I've also verified this on my UBUNTU machine, it has build successfully. Have you tried clean build project? Maybe it's because you have catkin_make outside of the docker before, try remove everything under the `ros/build` directory and `catkin_make` again.

**Comment by Mornor** [comment]
@olala7846 Yes, that has fixed my issue. Thanks!

**Pull request merged**
