### PR TITLE
Waypoint Updater Partial

### PR DESCRIPTION
**Pull request by lowspin**
Use ```rostopic echo /final_waypoints``` to see published (partial) waypoints

### CODE REVIEW

**Comment by joanxiao** [comment]
merged

**Comment by carlosgalvezp** [comment]
This shouldn't be a PR to Udacity, but to your team's repo...

**Comment by ckirksey3** [comment]
Pretty sure this was made by mistake..

**Comment by lowspin** [comment]
Sorry! My mistake. Thanks!

**Pull request closed without merging**
