### PR TITLE
Fix waypoints at test site

### LINKED ISSUE #71: Fix CSV file of waypoints for the test track
They are specified in the wrong order, as discussed on Slack.
The only thing available to us is the rosbag `udacity_succesful_light_detection.bag`, from which we should listen to `/base_waypoints` and generate our own CSV file.

Please release an official CSV file, or update the documentation to point students on what to do.

### PR DESCRIPTION
**Pull request by carlosgalvezp**
Extracted from `udacity_succesful_light_detection.bag`,
using the following code in `waypoint_updater.py`:

    with open('data/churchlot_with_cars.csv', 'w+') as fd:
        for waypoint in self.waypoints:
            x = waypoint.pose.pose.position.x
            y = waypoint.pose.pose.position.y
            z = waypoint.pose.pose.position.z
            q = waypoint.pose.pose.orientation
            q_array = [q.x, q.y, q.z, q.w]
            _, _, yaw = tf.transformations.euler_from_quaternion(q_array)
            fd.write('{},{},{},{}\n'.format(x, y, z, yaw))

Fixes #71

### CODE REVIEW

**Comment by carlosgalvezp** [comment]
Obtained from 'udacity_succesful_light_detection.bag',
using the following code in `waypoint_updater.py`:

with open('data/churchlot_with_cars.csv', 'w+') as fd:
    for waypoint in self.waypoints:
        x = waypoint.pose.pose.position.x
        y = waypoint.pose.pose.position.y
        z = waypoint.pose.pose.position.z
        q = waypoint.pose.pose.orientation
        q_array = [q.x, q.y, q.z, q.w]
        _, _, yaw = tf.transformations.euler_from_quaternion(q_array)
        fd.write('{},{},{},{}\n'.format(x, y, z, yaw))

**Comment by carlosgalvezp** [comment]
@ckirksey3 this PR is intended to be merged in Udacity master. I would be good if you guys could have a look at it!

**Comment by ckirksey3** [comment]
Will do, @carlosgalvezp! I need a chance to get this on the test track and try it out. Hopefully I'll have it reviewed and merged by Wednesday. Thanks a ton for your contribution.

**Comment by ckirksey3** [comment]
@carlosgalvezp, we tested out the new waypoint file and didn't actually see a difference in behavior with the changes. It's possible that something was off on our side. @swwelch is going to dive deeper into this problem to understand what's going on before approving the changes

**Comment by carlosgalvezp** [comment]
@ckirksey3 You mentioned the following on Slack (https://carnd.slack.com/archives/C6NVDVAQ3/p1506354717000478?thread_ts=1506156330.000011&cid=C6NVDVAQ3)

Caleb Kirksey [17 days ago] 
Here's a bag with the vehicle behaving correctly in autonomous mode (including correct waypoint order and traffic light classification): https://drive.google.com/open?id=0B2_h37bMVw3iT0ZEdlF4N01QbHc

I didn't quite follow the discussion about why the points were originally in the incorrect order, but I assumed the rosbag contained the ones in correct order.

In our case, our code works in such a way that it only process the image if the traffic light is close to the car and in front of it. With the old waypoints, we would start processing images where there was no traffic light at all; with the new ones, everything matches and we process images only when there's actually a visible light.

**Comment by 9mat** [comment]
just to add in to carlosgalvezp, I've drawn the position of the car in the rosbag and it follows pretty close to these waypoints (and in the correct order), whereas the old waypoints the card is far off the waypoints. The rosbag play is recorded [here](https://www.youtube.com/watch?v=4VcQpIqlacQ)

**Comment by jwdunn1** [comment]
In conjunction with this fix, please correct the stop line in the site_traffic_light_config.yaml file. It should be roughly (13.8239, 18.2032) so as to be in line with the waypoint list.

**Comment by carlosgalvezp** [comment]
@jwdunn1 Thanks for the feedback! Before adding the change, would you mind pointing me to the source of this information? I would like to have some official statement from Udacity. Maybe @ckirksey3 knows?

**Comment by jwdunn1** [comment]
My request/suggestion comes from data analysis. I would like Caleb to confirm my findings. Whereas the simulator has stop lines along the waypoint path, the test site has a "stop line" positioned at the actually traffic light. The nearest waypoint to the traffic light is on the curve where the traffic light would no longer be visible. One way to mitigate this would be to stop four waypoints prior. Here is an annotated map in my team's wiki: https://github.com/level5-engineers/system-integration/wiki/Site-Test

**Comment by carlosgalvezp** [comment]
Thanks for the analysis! One concern though: why are our points different than Team Vulture's? I extracted these points from `udacity_succesful_light_detection.bag`, which should be the same as Team Vulture's

**Comment by jwdunn1** [comment]
Team Vulture's readme refers to `loop_with_traffic_light.bag`. The bag you are referring to (`udacity_succesful_light_detection.bag`) is the one recorded from Team Vulture's successful run on Carla. Therefore, it is more recent.

**Comment by carlosgalvezp** [comment]
Ah yes, that's correct.

**Comment by carlosgalvezp** [comment]
Since @ckirksey3 is no longer working at Udacity, could @swwelch have a look? Maybe also Yousof but I can't find him here :)

**Comment by jwdunn1** [comment]
@carlosgalvezp, I think you mean Yous**u**f: @spicavigo

**Comment by carlosgalvezp** [comment]
Oops, typo there, thanks @jwdunn1

**Comment by swwelch** [comment]
Sorry for the extremely long delay on this. On the test site we occasionally record new waypoints, and the launch script on the car is set up to replace any waypoint file with the new waypoint file we've recorded. I'll upload the current waypoint file we are loading when testing the car, but they may differ slightly from waypoints found in `udacity_succesful_light_detection.bag`.

**Comment by swwelch** [comment]
I believe this has been addressed now with updates in the classroom, so I'm going to close this PR.

**Pull request closed without merging**
